### ISSUE TITLE
视频加水印崩溃

### ISSUE THREAD

**Issue by chenxihoulang** [tangyxgit/FFmpegVideo#11]
有的视频添加水印会崩溃,崩溃日志:
07-30 12:18:34.787 865-996/? E/NativeCrashListener: Exception dealing with report
    android.system.ErrnoException: read failed: EAGAIN (Try again)
        at libcore.io.Posix.readBytes(Native Method)
        at libcore.io.Posix.read(Posix.java:165)
        at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
        at android.system.Os.read(Os.java:350)
        at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
        at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)

**Comment by tangyxgit** [comment]
视频是否很大?转ts流正常吗？demo只支持arm，确认一下



发送自我的三星盖乐世智能手机。


-------- 原始信息 --------
发件人： 晨曦后浪 <notifications@github.com>
日期: 2019/7/30 12:30 (GMT+08:00)
收件人： tangyxgit/FFmpegVideo <FFmpegVideo@noreply.github.com>
抄送： Subscribed <subscribed@noreply.github.com>
主题： [tangyxgit/FFmpegVideo] 视频加水印崩溃 (#11)


有的视频添加水印会崩溃,崩溃日志:
07-30 12:18:34.787 865-996/? E/NativeCrashListener: Exception dealing with report
android.system.ErrnoException: read failed: EAGAIN (Try again)
at libcore.io.Posix.readBytes(Native Method)
at libcore.io.Posix.read(Posix.java:165)
at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
at android.system.Os.read(Os.java:350)
at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)

―

**Comment by chenxihoulang** [comment]
视频大小2.36M,视频时长15秒,我这里所有的手机针对这个视频加水印or转ts都会崩溃,其他视频是正常的?我要如何确认问题在哪里?怎么确定这个视频到底是哪里的问题?

**Comment by tangyxgit** [comment]
把崩溃日志贴来看看




发送自我的三星盖乐世智能手机。


-------- 原始信息 --------
发件人： 晨曦后浪 <notifications@github.com>
日期: 2019/7/30 17:59 (GMT+08:00)
收件人： tangyxgit/FFmpegVideo <FFmpegVideo@noreply.github.com>
抄送： GalaxyYx <tangyx@live.com>, Comment <comment@noreply.github.com>
主题： Re: [tangyxgit/FFmpegVideo] 视频加水印崩溃 (#11)


视频大小2.36M,视频时长15秒,我这里所有的手机针对这个视频加水印or转ts都会崩溃,其他视频是正常的?我要如何确认问题在哪里?怎么确定这个视频到底是哪里的问题?

―

**Comment by chenxihoulang** [comment]
[1564455624210271.mp4.zip](https://github.com/tangyxgit/FFmpegVideo/files/3446246/1564455624210271.mp4.zip)
就是上面这个视频

**Comment by tangyxgit** [comment]
你这个看着不想程序崩溃日志，系统日志吧这是



发送自我的三星盖乐世智能手机。


-------- 原始信息 --------
发件人： 晨曦后浪 <notifications@github.com>
日期: 2019/7/30 12:30 (GMT+08:00)
收件人： tangyxgit/FFmpegVideo <FFmpegVideo@noreply.github.com>
抄送： Subscribed <subscribed@noreply.github.com>
主题： [tangyxgit/FFmpegVideo] 视频加水印崩溃 (#11)


有的视频添加水印会崩溃,崩溃日志:
07-30 12:18:34.787 865-996/? E/NativeCrashListener: Exception dealing with report
android.system.ErrnoException: read failed: EAGAIN (Try again)
at libcore.io.Posix.readBytes(Native Method)
at libcore.io.Posix.read(Posix.java:165)
at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
at android.system.Os.read(Os.java:350)
at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)

―

**Comment by chenxihoulang** [comment]
07-30 12:18:32.695 12588-12722/com.acceptance E/chromium: ### WebView Version Developer Build (code 1)
07-30 12:18:32.695 12588-12722/com.acceptance A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1 in tid 12722 (AsyncTask #4)
07-30 12:18:34.787 865-996/? E/NativeCrashListener: Exception dealing with report
    android.system.ErrnoException: read failed: EAGAIN (Try again)
        at libcore.io.Posix.readBytes(Native Method)
        at libcore.io.Posix.read(Posix.java:165)
        at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
        at android.system.Os.read(Os.java:350)
        at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
        at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)
我这看到的日志就这些
